#!/usr/bin/env bash
# Install nginx on your web-01
# nginx should be listen at port 80
# querying Nginx at its root / with a GET request (requesting a page) using curl
# it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
