#!/usr/bin/env bash
# A Bash script that manages 'manage_my_process'
# This script works based on passed in command line arguments
# Command line arguments should be:
# start , stop , restart

# Checking for argument counts
if [ $# -gt 0 ]
then
        # If the first argument is "start"
        if [ "$1" == "start" ]
        then
                ./manage_my_process &     # Starting the 'manage_my_process' process
                touch /var/run/my_process.pid     # Create /var/run/my_process.pid
                echo "$!" > /var/run/my_process.pid     # Creating a file contains its own PID
                echo "manage_my_process started"     # Displays "manage_my_process started"

        # If the first argument is "stop"
        elif [ "$1" == "stop" ]
        then
                echo "manage_my_process stopped"     # Displays "manage_my_process stopped"
                kill "$(cat /var/run/my_process.pid)"     # Kills the 'manage_my_process' by using its PID (Essence of the 'cat' command)
                rm -f /var/run/my_process.pid     # Forcefully deletes /var/run/my_process.pid

        # If the first argument is "restart"
        elif [ "$1" == "restart" ]
        then
                kill "$(cat /var/run/my_process.pid)"     # Kills the 'manage_my_process' by using its PID (Essence of the 'cat' command)
                rm -f /var/run/my_process.pid     # Forcefully deletes /var/run/my_process.pid
                ./manage_my_process &     # Starting the 'manage_my_process' process again
                touch /var/run/my_process.pid     # Create /var/run/my_process.pid
                echo "$!" > /var/run/my_process.pid     # # Writing the PID of /var/run/my_process.pid into /var/run/my_process.pid
                echo "manage_my_process restarted"     # Displays "manage_my_process restarted"

        # If any other argument or no argument is passed
        else
                # Display "Usage: manage_my_process {start|stop|restart}"
                echo "Usage: manage_my_process {start|stop|restart}"
        fi
# If any other argument or no argument is passed
else
        # Display "Usage: manage_my_process {start|stop|restart}"
        echo "Usage: manage_my_process {start|stop|restart}"
fi