#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line
count=1
while [ "$count" -le 10 ]; do
    echo "Best School"
    if [ "$count" -eq 9 ]
    then
        echo "Hi"
    fi
    count=$((count + 1))
done
