#!/usr/bin/env bash
# This script is displaying 'bad lack' on 4th loop iteration, 'good luck' on 8th loop and 'Best School' on other iterations
count=1
while [ "$count" -le 10 ]; do
    if [ "$count" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$count" -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
