#!/usr/bin/env bash
# script that configures Ubuntu server
cp /etc/hosts ~/hosts.new

# Resolving localhost to 127.0.0.2.
echo "127.0.0.2		localhost" > ~/hosts.new

# Resolving facebook.com to 8.8.8.8
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Forcing this command
cp -f ~/hosts.new /etc/hosts
